### ISSUE TITLE
Import data - No se crea otra carpeta de proyecto nuevo al importar INP

### ISSUE THREAD

**Issue by Ostoveni** [neslerel/BetaTesters_QGRed#2]
Hola a todos

He estado jugando un poco "al usuario tonto" con esta opción de import data.
Sucede lo siguiente:

1. Tengo abierto una red cualquiera en QGISRed
2. Decido importar un modelo de red de Epanet (Inp) y se "borrar" la información almacenada de la red abierta por el nuevo modelo de red importado.

Sugerencia:

Cuando se invoque al formulario de importar, dejar los casilleros en blanco para que el usuario se vea obligado a rellenarlos. Así se evitará machacar los datos de cualquier red abierta y se creará un nuevo proyecto y se visualizará en el Gestor de Proyectos. Adjunto foto.

![FIG1](https://user-images.githubusercontent.com/20848965/68993969-96abd800-087d-11ea-80c4-3016cfd16e9d.png)

**Comment by neslerel** [comment]
Buenos días Óscar,

En la importación del INP considero que no es posible completar con información previa, de ahí que se borre todo el contenido actual del proyecto y se incluya únicamente lo del INP. Sin embargo, en la importación de información de SHPs es al contrario, es incremental. Puedes importar unas tuberías y luego otras (u otros elementos).

Para evitar la confusión o, mejor dicho, el problema de ver como la información previa que tenías desaparece, he añadido una pregunta antes de importar el INP. De esa manera informo al usuario de que se va a borrar todo y si quiere continuar:

![2019-11-18_07-45-12](https://user-images.githubusercontent.com/14369655/69030427-e0103a80-09d7-11ea-8847-b071aa065dc2.gif)


¿Cómo lo veis?

**Comment by Ostoveni** [comment]
Buenos días Néstor

En la figura que adjunto sugiero que se añada un botón (recuadro rojo) donde el usuario seleccione el nuevo directorio de proyecto para importar otro modelo de red (formato Inp), después de darle al botón NO del cuadro de diálogo que has creado. Así, el usuario podrá ejecutar la tarea sin necesidad de salir del formulario (QGISRed: Import)

![FIG5](https://user-images.githubusercontent.com/20848965/69201190-c12bb880-0b3d-11ea-8282-6d28f309281b.png)

**Comment by Ostoveni** [comment]
He visto que ese botón que "falta" desaparece cuando ya tiene abierto una red en el visor de mapa .

**Comment by neslerel** [comment]
A ver, yo creo que si realmente quieres importar un INP no tiene sentido tener otro proyecto abierto... lo lógico sería cerrar el que tienes y empezar uno nuevo.
Efectivamente, cuando ya existe un modelo impido que se pueda cambiar tanto el nombre de la red como el directorio donde está.
Creo que con el mensaje de advertencia para que el usuario no pierda información es suficiente. Si ocurre eso, basta con que cierre el proyecto actual y le vuelva a dar a importar (creándose uno nuevo).
