### ISSUE TITLE
Import data - Caso Net3 - No copia todas las leyes de control simple

### ISSUE THREAD

**Issue by Ostoveni** [neslerel/BetaTesters_QGRed#3]
Hola a todos

Al momento de importar la red Net3 he comprobado que no copia todas las leyes de control. 
Una de las posibles causas en el código podría ser que no se ha considerado los espacios en blanco y los puntos y comas al momento de leer toda la información que cuelga de la sección [CONTROLS]

![FIG2](https://user-images.githubusercontent.com/20848965/68995791-e72d3080-0891-11ea-8cc9-cec09bca3a7e.png)

**Comment by neslerel** [comment]
Listo, un error en la mayúsculas y minúsculas...

![qgis-bin_2019-11-18_07-55-28](https://user-images.githubusercontent.com/14369655/69030801-df2bd880-09d8-11ea-8b08-81f931d69452.png)

**Comment by Ostoveni** [comment]
Para este modelo de red, aún no se copia la ley de control.

![FIG1](https://user-images.githubusercontent.com/20848965/69201479-bc1b3900-0b3e-11ea-9ecb-3b098943b491.png)

**Comment by neslerel** [comment]
No tengo ese modelo, pero he probado a escribir esa ley de control exactamente igual y sí que me la carga. ¿En el modelo existe la 'VALVE-180'?

**Comment by Ostoveni** [comment]
La válvula existe

![FIG1](https://user-images.githubusercontent.com/20848965/69227958-058d7780-0b83-11ea-8a32-5af357522fb7.png)


Te adjunto el modelo para que lo mires

**Comment by neslerel** [comment]
Prueba: [control.zip](https://github.com/neslerel/BetaTesters_QGRed/files/3868516/control.zip)

**Comment by Ostoveni** [comment]
[2_BWSN_Network_1.zip](https://github.com/neslerel/BetaTesters_QGRed/files/3868524/2_BWSN_Network_1.zip)
