### ISSUE TITLE
Import data - Caso Chetumal (Red Mexicana) - Varias cosas

### ISSUE THREAD

**Issue by Ostoveni** [neslerel/BetaTesters_QGRed#4]
**1. Visualización de puntos de demandas (color rojo) cuando no tiene el check (adjunto foto)**

![FIG3](https://user-images.githubusercontent.com/20848965/68996059-43de1a80-0895-11ea-9666-71713c9cc4a4.png)

**2.  Importación de leyes de control no completas**

![FIG4](https://user-images.githubusercontent.com/20848965/68996156-abe13080-0896-11ea-8b46-47c1797a6392.png)

**3. Redondeo a tres decimales (campo demanda base) en los nudos de caudal**
Sólo es avisar que en el modelo INP de Epanet hay muchos más decimales que en un proyecto GISRed. Sé que está redondeado a tres decimales. Pienso que se debe copiar todos los decimales.

![FIG5](https://user-images.githubusercontent.com/20848965/68996333-e8159080-0898-11ea-9912-6a3005fee1eb.png)

**4. Sugerencia.**

Cuando se importa un modelo de red sea de INP o Shape, el campo material debería quedar vacío.
El usuario podrá rellenarlo de manera manual más adelante. Epanet no cuenta con esta propiedad

![FIG6](https://user-images.githubusercontent.com/20848965/68996400-b18c4580-0899-11ea-9853-93b816a3c843.png)

**Comment by neslerel** [comment]
Hola, comento cada punto:
1.- La capa Junctions, al igual que en Epanet, también incluye una demanda base y un Id de la curva de modulación (Pattern). Los junctions que tienen una demanda base distinta de 0 aparecen en rojo (independientemente de la capa de Demands).
La capa de Demands es por si quieres incluir más de una demanda base o curva de modulación en un único nudo. En ese caso, basta con dibujar varios puntos superpuestos sobre un nudo, asignarle el valor de demanda base y el Id del Pattern (o bien hacerlo mediante la ventana de edición de propiedades, mucho más sencillo).

2.- Solucionado.

3.- Este es un aspecto a discutir. Se pueden añadir, pero ¿tiene sentido tantos decimales?

4.- El material, si no utilizas la herramienta de estimar al rugosidad o juntar tuberías no se emplea (de momento). Podría establecerse por defecto como UNKNOWN y que el usuario luego asigne el que quiera. ¿Opiniones?

**Comment by Ostoveni** [comment]
**1. Ya no aparecen los puntos rojos (¿hiciste algo?)**

![FIG1](https://user-images.githubusercontent.com/20848965/69201781-bf62f480-0b3f-11ea-9007-7dd24b14472d.png)

**2. Aún falta pasar más leyes de control. Sigue copiando sólo AT CLOCKTIME**

![FIG2](https://user-images.githubusercontent.com/20848965/69201903-35fff200-0b40-11ea-8052-15c998dd0580.png)

**3. De los decimales, Fernando tiene que pronunciarse**

**4. Opino que debería asignarse UNKNOWN.**

**Comment by neslerel** [comment]
1.- No, no he tocado nada. Simplemente tienes desactivada también la capa de Junctions, de ahí que no aparezcan puntos ni negros, ni rojos.
2.- Según el manual de EPANET no pone que se pueda escribir "IF TANK"... Este Fernando...
![image](https://user-images.githubusercontent.com/14369655/69215366-c999e880-0b69-11ea-9439-6a94f12c29b4.png)
Ya lo he corregido. A ver si en la siguiente versión funciona (o pásame el o los INP y lo pruebo).

**Comment by Ostoveni** [comment]
[Chetumal Condicion Actual.zip](https://github.com/neslerel/BetaTesters_QGRed/files/3868830/Chetumal.Condicion.Actual.zip)
