### ISSUE TITLE
Al cerrar la ventana de resultados, se desactiva grupo de capas "Results"

### ISSUE THREAD

**Issue by Ostoveni** [neslerel/BetaTesters_QGRed#47]
He comprobado que al cerrar el panel "QGISRed Results" se deja de seleccionar el grupo de capas "Results" y se selecciona el otro grupo de capas "Inputs". Hasta ahí todo bien.
Cuando quiero que aparezca nuevamente el panel "QGISRed Results" el grupo de capas "Results" no se selecciona, lo cual da la impresión de que hay que volver a ejecutar la simulación.

![Volver_a_ejecutar_Simulacion](https://user-images.githubusercontent.com/20848965/70189871-c0298800-16f4-11ea-820c-8e884a35d625.png)

![VentanaResultadosSimulCerrada](https://user-images.githubusercontent.com/20848965/70189880-c586d280-16f4-11ea-9bbc-39c0a3fc8e84.png)

![Mapa_no_se_actualiza](https://user-images.githubusercontent.com/20848965/70189889-cddf0d80-16f4-11ea-9d3b-af272caf275b.png)

**Comment by neslerel** [comment]
Sí, he intentado que fuese intuitivo, pero se me ha olvidado la posibilidad de abrir el dock de resultados de forma manual. Tengo que controlar eso y volver a activar la capa de resultados y desactivar la de Inputs.
También puede activarla el usuario indistintamente.
Y queríamos crear un botón junto al de simular que fuese solo para mostrar ese menú de resultados.

**Comment by neslerel** [comment]
Solucionado. Ya controlo cuando se abre o se cierra el dock de resultados para habilitar o deshabilitar los grupos de capas de Results e Inputs.
Además, he creado el botón para acceder fácilmente al menú de resultados sin tener que simular y sin tener que buscarlo en las opciones de QGis
![image](https://user-images.githubusercontent.com/14369655/71992499-c0f29400-3235-11ea-85c0-5367983dcf03.png)

El icono en sí, es el primero que he cogido que tenía por ahí, sería cosa de cambiarlo por algo mejor.

**Comment by Ostoveni** [comment]
¿La opción "Show Results Browser" está en la versión 0.8.1?

**Comment by neslerel** [comment]
Sí, debería:
![image](https://user-images.githubusercontent.com/14369655/72781052-a6022580-3c20-11ea-9b62-d6910d063b3a.png)
![image](https://user-images.githubusercontent.com/14369655/72781068-b87c5f00-3c20-11ea-8d78-4e8baa9880af.png)

El único sitio donde no está:
![image](https://user-images.githubusercontent.com/14369655/72781089-c500b780-3c20-11ea-91da-53c1da692fd2.png)

**Comment by Ostoveni** [comment]
Vale, no había revisado que estaba en la barra de menú o cuando se desea desplegar todos los botones de acceso rápido.
