### ISSUE TITLE
Panel "QGISRed Results" no movible

### ISSUE THREAD

**Issue by Ostoveni** [neslerel/BetaTesters_QGRed#48]
Al utilizar la opción identificación de objetos espaciales (botón con una flecha y una i) sobre un elemento de nudo de caudal, el panel se ubica en la izquierda por encima del panel "QGISRed Results" donde éste último no se puede mover hacia abajo para poder visualizar todos los parámetros del elemento seleccionado.

![Paneles_movibles](https://user-images.githubusercontent.com/20848965/70190418-27940780-16f6-11ea-8370-29804681a659.png)

**Comment by neslerel** [comment]
Interesante apreciación... Siempre se puede cerrar o mover a otro lado cualquiera de los docks... Pero sí, hay que estudiar cómo permitir que el de resultados se pueda hacer pequeño.

**Comment by neslerel** [comment]
Arreglado! En la próxima versión ya se podrá ampliar y comprimir.
