### ISSUE TITLE
Reordenación capas tras operaciones de edición

### ISSUE THREAD

**Issue by fmartine** [neslerel/BetaTesters_QGRed#50]
Para una buena visibilidad de todos los elementos, la capa más profunda debe ser la de tuberías, a continuación la de junctions, después bombas y válvulas, y finalmente embalses y depósitos. 
Al crear o  borrar bombas y válvulas, y refrescar, se pierde ese orden y junctions queda encima de bombas y válvulas, lo que afecta a la visibilidad de éstas últimas.
Dejar siempre junctions justo encima de las tuberías.

**Comment by neslerel** [comment]
Realmente siempre lo ordenaba de la misma forma. Ya está cambiado para que sea:
Embalses
Depósitos
Sources
Demandas Múltiples
Bombas
Válvulas
Junctions
Tuberías

**Comment by fmartine** [comment]
Podría ser el siguiente orden?:
Sources
Embalses
Depósitos
Bombas
Válvulas
Demandas Múltiples
Junctions
Tuberías

Las demadas múltiples debería ir superpuestas a continuación de los junctions por su relación, y las sources en lo más alto, pues los depósitos y embalses suelen ser sources y el simbolo de éstos (más compacto) podría ocular a las sources (una estrella)

**Comment by neslerel** [comment]
Cambiado
