### ISSUE TITLE
Error al usar un fichero *.asc para interporlar las cotas

### ISSUE THREAD

**Issue by nimonro** [neslerel/BetaTesters_QGRed#6]
Hola a partir de un archivo shp de curvas de nivel he generado un asc. El proceso no me ha generado ninguna falla, pero sí a la hora de utilizar el asc con QGisred para interpolar las cotas.
¿Se requiere algún formato específico de asc? Incluyo imagen del error que me devuelve.

[Pantallazos.docx](https://github.com/neslerel/BetaTesters_QGRed/files/3854590/Pantallazos.docx)

**Comment by neslerel** [comment]
Gracias Nicolás!

Había un error en la selección de los ficheros .asc por parte del usuario. Es un error que viene de la migración de la versión 2 o a la 3 de QGis. Desde que lo programé inicialmente no había vuelto a usar la herramienta.

Además, el archivo asc tiene que tener el siguiente formato:
![notepad++_2019-11-18_08-17-29](https://user-images.githubusercontent.com/14369655/69032074-f15b4600-09db-11ea-9370-f1e537b9b191.png)

**Comment by nimonro** [comment]
> Gracias Nicolás!
> 
> Había un error en la selección de los ficheros .asc por parte del usuario. Es un error que viene de la migración de la versión 2 o a la 3 de QGis. Desde que lo programé inicialmente no había vuelto a usar la herramienta.
> 
> Además, el archivo asc tiene que tener el siguiente formato:
> ![notepad++_2019-11-18_08-17-29](https://user-images.githubusercontent.com/14369655/69032074-f15b4600-09db-11ea-9370-f1e537b9b191.png)

Hola Néstor,
Mi .asc si tiene ese formato, lo único que para falta de valores yo le puse 0 y me lo completa con muchos ceros. No sé hasta qué punto afecte eso a la herramienta.

Por otro lado dices que había un error en la selección de los ficheros. ¿Tengo manera de solventar ese error? ¿Tienes que modificar algo en el código?

Gracias.

**Comment by neslerel** [comment]
Respecto a tu valor para datos faltantes, no creo que sea un problema que pongas 0 en vez de otro número...
Sí, he tenido que cambiar el código del plugin. En breve os enviaré por email otra versión beta. Supongo que mañana por la mañana.

Saludos

**Comment by nimonro** [comment]
Hola Néstor,

Estoy probando con la nueva versión pero me sigue dando un error. 

Error: en System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal) en System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info) en GISRed.Model.Scenario.GetElevationsFromAsci(IReadOnlyCollection`1 rutasAsci, List`1 elementosPuntuales, Logger logger) en GISRed.QGisPlugins.QGisPlugins.ElevationInterpolation(String dirPath, String networkName, String elevationFiles)

Y mi fichero asc es de este tipo:

ncols        26668
nrows        21964
xllcorner    350510.441899999976
yllcorner    3495556.663000000641
cellsize     1.000000000000
NODATA_value  0
 0.0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

Luego corrijo lo de los ceros.

¿Me puedes orientar por donde puede ir el problema?

Gracias.

**Comment by neslerel** [comment]
Hola Nicolás,

Mándame por favor el archivo .asc (por aquí si deja o por email) y lo pruebo. Lo he probado con los datos que me has pasado y no me da error...
Supongo que entre toda la matriz de datos, habrá algún blanco o algún carácter que no sea número y por eso de error.

Saludos,

**Comment by neslerel** [comment]
Vale, al final el problema estaba en que las 6 primeras líneas tenían espacios múltiples entre la etiqueta y el valor. Ya está corregido para la próxima versión.
