### ISSUE TITLE
Error en tabla de contenidos (capas) y el área de mapa

### ISSUE THREAD

**Issue by Ostoveni** [neslerel/BetaTesters_QGRed#60]
Acabo de visualizar un fallo en la tabla de contenido y el área de dibujo.
Después de ejecutar una simulación sobre la NET1 he realizado un cambio en el visor de resultados sobre las variables velocidad y calidad de agua y se van añadiendo capas de resultados de la calidad, lo mismo en el área de mapa con los resultados.
Adjunto imagen

![Errores en el panel de contenido y el mapa](https://user-images.githubusercontent.com/20848965/93265487-f712eb00-f7a8-11ea-8a48-eefa7e88e8a5.png)

**Comment by neslerel** [comment]
Gracias Óscar. Ya lo he conseguido replicar, menos mal que solo pasa al seleccionar los resultados de calidad. Voy a ver si lo arreglo.

**Comment by neslerel** [comment]
Ya está arreglado.
