### ISSUE TITLE
Actualizar fórmula de pérdida de carga (Barra de estado)

### ISSUE THREAD

**Issue by Ostoveni** [neslerel/BetaTesters_QGRed#61]
Después de utilizar la opción de cambiar los coeficientes de rugosidad, en la barra de estado hace falta actualizarla por la nueva fórmula de pérdidas seleccionada (adjunto imagen)
Sugerencia: Debería estar sólo la opción final de cambiar de fórmula de pérdida de carga. 
Quizá podría generar confusión al usuario, pensando que debe seleccionar alguna opción.

![Actualizar-cambios-barra-estado-Conversor-rugosidades](https://user-images.githubusercontent.com/20848965/93266844-0430d980-f7ab-11ea-9516-0df572a5f06b.png)

**Comment by Ostoveni** [comment]
Una observación más.
Al cerrar un proyecto de redes de agua trabajado con QGISRed y posteriormente abrimos QGIS, me aparece en la barra de estado la unidad de caudal y fórmula de pérdida de carga por defecto "LPS | HW".
Creo que esa barra de estado debería aparecer si se abre el proyecto desde el gestor.
He abierto un proyecto .qgz y también me aparece la barra de información de la unidad de caudal y fórmula de pérdidas por defecto, que no coincide con la información original.

![Imagen](https://user-images.githubusercontent.com/20848965/93269574-8ae7b580-f7af-11ea-87b1-b31174271822.png)

**Comment by neslerel** [comment]
La herramienta está pensada para que se convierta la rugosidad de una fórmula a otra, indistintamente de la que esté definida en las opciones del proyecto.
Si vemos que a la gente le confunde podemos simplificarlo haciendo que solo se seleccione la fórmula a la que se quiere convertir.

Respecto a lo de la barra de estado. Es un poco igual que el resto de botones, se ven aunque no puedas usarlos si no está el proyecto abierto. Lo que sí que hay que arreglar es al abrir un proyecto con QGis que sea a la vez de QGISRed, se actualice correctamente.

**Comment by neslerel** [comment]
Lo de la barra de estado ya se actualiza al cargar un proyecto de QGis.
