### ISSUE TITLE
Colores gráfico Patterns

### ISSUE THREAD

**Issue by neslerel** [neslerel/BetaTesters_QGRed#8]
De Fernando: 

> Por otra parte, el valor medio en trazo continuo igual quedaría mejor, dándole el color complementario. Todos los colores tienen su complementario y es el que mejor contrasta con él al superponerlo. En internet debe estar la lista de colores complementarios (ver teoría del color). Creo que se obtienen modificando el código RGB ó el HSV siguiendo cierta regla.
Sobre los colores complementarios y la estética, en este enlace lo cuenta bastante bien, aunque no viene la regla automática para generarlos. Parece una tontería, pero si se sabe, cuesta muy poco
elegir otro color que combine, no hay que ir probando, y el resultado es mucho mejor con el mismo trabajo. Es solo una cuestión de saberlo o no saberlo.
https://es.wikipedia.org/wiki/Colores_complementarios

**Comment by neslerel** [comment]
Listo
![2019-11-26_09-21-39](https://user-images.githubusercontent.com/14369655/69611547-49262c80-102e-11ea-902d-247411968916.gif)

**Comment by fmartine** [comment]
Creo que queda muy bien. Mejor que antes. Quizás reduciría muy poquito el grosor de la línea del valor medio, ya que estás utilizando un trazo fino para todo.

**Comment by neslerel** [comment]
Vale, al principio me parecía muy fina y la había engordado un poco. La he pasado de grosor 5 a 2:
![image](https://user-images.githubusercontent.com/14369655/69702553-c9609680-10ef-11ea-8431-099c52407749.png)

Creo que se ve bien, pero sino, se puede subir a 3.

**Comment by fmartine** [comment]
Perfecto. Déjala así. Por mi parte puedes cerrar este issue
